-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        inactive_opacity = 0.9,
        shadow = {
            enabled = false,
        },
    },
    general = {
        gaps_in = 2,
        gaps_out = 2,
    },
    input = {
        touchpad = {
            scroll_factor = 0.3,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Monitors
-- Note: this file is regenerated by the Hyprland settings GUI.
-- Kept in sync with monitors.lua (Dell S2421HN at its max refresh).
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "1920x1080@74.97Hz",
    position = "0x-1080",
    scale = 1,
    cm = "srgb",
})
