-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        inactive_opacity = 0.95,
        shadow = {
            enabled = false,
        },
    },
    general = {
        gaps_in = 2,
        gaps_out = 2,
    },
})
