-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        inactive_opacity = 0.9,
        shadow = {
            enabled = false,
        },
    },
    general = {
        gaps_in = 2,
        gaps_out = 2,
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})
