-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:

local monitors = require("monitors")
local programs = require("programs")
local autostart = require("autostart")
local environment = require("environment")
local permissions = require("permissions")
local look_and_feel = require("look-and-feel")
local misc = require("misc")
local input = require("input")
local windows_and_workspaces = require("windows-and-workspaces")

-- Expose program variables globally for use in keybindings
terminal    = programs.terminal
fileManager = programs.fileManager
menu        = programs.menu
browser     = programs.browser

local keybindings = require("keybindings")


-----------------
---- MONITORS ----
-----------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/


--------------------
---- MY PROGRAMS ----
--------------------

-- Set programs that you use


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/


------------------------------
---- ENVIRONMENT VARIABLES ----
------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/


--------------------
---- PERMISSIONS ----
--------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons


----------------------
---- LOOK AND FEEL ----
----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/


--------------------
---- MISC ----
--------------------

--


---------------
---- INPUT ----
---------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/


--------------------
---- KEYBINDINGS ----
--------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/


-----------------------
---- WINDOWS AND WORKSPACES ----
-----------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
