-- Hyprland entry point: orchestrate focused Lua modules.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

require("monitors")
require("input")
require("environment")
require("appearance")
require("animations")
require("wallpaper")
require("windowrules")
require("keybindings")
require("autostart")

-- HyprMod managed settings. pcall: the file is Git-ignored (generated by
-- HyprMod, per-machine state), so a fresh checkout may not have it yet —
-- HyprMod creates it on its first save.
pcall(require, "hyprland-gui")
