# Formato:
# app|manager|packages
#
# - app: nome do pacote stow neste repositorio.
# - manager: pacman ou aur.
# - packages: lista de pacotes separados por espaco.
#
# O grupo _base sempre e incluido para garantir o minimo necessario
# antes de executar stow.

_base|pacman|base-devel git stow

btop|pacman|btop
code-flags|pacman|code
dunst|pacman|dunst
git|pacman|git
gtk|pacman|gtk2 gtk3
hypridle|pacman|hypridle
hyprland|pacman|hyprland hyprpaper xdg-desktop-portal-hyprland xdg-desktop-portal-gtk qt5-wayland qt6-wayland wl-clipboard wlr-randr grim slurp swappy hyprpicker brightnessctl thunar lxqt-policykit pipewire wireplumber pamixer pavucontrol networkmanager network-manager-applet bluez bluez-utils wlogout mako swaync
hyprlock|pacman|hyprlock
keyd|pacman|keyd
kitty|pacman|kitty ttf-jetbrains-mono-nerd
libinput|pacman|libinput
nvim|pacman|neovim git ripgrep fd unzip lazygit nodejs npm gcc
starship|pacman|starship
tmux|pacman|tmux
waybar|pacman|waybar python python-requests otf-font-awesome
wofi|pacman|wofi
yay|aur|yay
zsh|pacman|zsh zsh-completions zsh-autosuggestions zsh-syntax-highlighting nvm rbenv ruby-build
